project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/capg-garbage-collector
  tag: "[[ .Version ]]"
  pullPolicy: IfNotPresent

pod:
  user:
    id: "65532"
  group:
    id: "65532"

gcpProject: ""
